# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/6184#note_283677909
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-ephemeral-storage
spec:
  limits:
  - default:
      ephemeral-storage: "4Gi"
    defaultRequest:
      ephemeral-storage: "300Mi"
    type: Container
